In [5]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define a model class
This model class is defined for dummy purposes. We don't use any actual training data for this model.
We use this class to demonstrate saving of models

In [12]:
# Define model
class SimpleNN(nn.Module):
    def __init__(self, D_in, H, D_out):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(D_in, H)
        self.fc2 = nn.Linear(H, D_out)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Initialize model and print state dict
We simply initialize a simpleNN model and display its weights

In [21]:
# Initialize model
model = SimpleNN(10, 5, 2)

# Initialize optimizer
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

In [22]:
model.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.2117,  0.0977,  0.1019,  0.1360, -0.0090,  0.1788,  0.2858,  0.0869,
                        0.2018, -0.3115],
                      [-0.0054, -0.0701,  0.0437, -0.0901,  0.1675, -0.0519,  0.0745,  0.2853,
                        0.0275, -0.1648],
                      [ 0.1453, -0.0004,  0.0510,  0.0302,  0.1480,  0.0504,  0.1632, -0.0638,
                        0.1941,  0.2771],
                      [-0.2011,  0.3143,  0.0317,  0.0947, -0.1041, -0.2499,  0.2555, -0.2850,
                       -0.1223,  0.0376],
                      [ 0.2990,  0.0105, -0.0436,  0.2773,  0.0673, -0.1720,  0.0293,  0.0463,
                       -0.1830,  0.0466]])),
             ('fc1.bias', tensor([0.0295, 0.2434, 0.0940, 0.0825, 0.0175])),
             ('fc2.weight',
              tensor([[ 0.3498,  0.1448,  0.2090, -0.2425, -0.2384],
                      [ 0.3390, -0.3021,  0.3031, -0.2717, -0.1913]])),
             ('fc2.bias', tensor([-0.2

In [23]:
# Print model's state_dict
print("Model's state_dict:")
for param_tensor in model.state_dict():
    print(param_tensor, "\t", model.state_dict()[param_tensor].size())

# Print optimizer's state_dict
print("Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Model's state_dict:
('fc1.weight', '\t', torch.Size([5, 10]))
('fc1.bias', '\t', torch.Size([5]))
('fc2.weight', '\t', torch.Size([2, 5]))
('fc2.bias', '\t', torch.Size([2]))
Optimizer's state_dict:
('state', '\t', {})
('param_groups', '\t', [{'dampening': 0, 'nesterov': False, 'lr': 0.001, 'params': [140549204243072, 140549204216240, 140549204215520, 140549204215680], 'weight_decay': 0, 'momentum': 0.9}])


# Save model state dict
We call mode.state_dict() and use torch.save() for saving it

In [34]:
torch.save(model.state_dict(), "simpleNN_state_dict.pt")

# Load and display model weights
Read model weights back from file and display it

In [35]:
model_weights_for_simpleNN = torch.load("simpleNN_state_dict.pt")
model_weights_for_simpleNN

OrderedDict([('fc1.weight',
              tensor([[ 0.2117,  0.0977,  0.1019,  0.1360, -0.0090,  0.1788,  0.2858,  0.0869,
                        0.2018, -0.3115],
                      [-0.0054, -0.0701,  0.0437, -0.0901,  0.1675, -0.0519,  0.0745,  0.2853,
                        0.0275, -0.1648],
                      [ 0.1453, -0.0004,  0.0510,  0.0302,  0.1480,  0.0504,  0.1632, -0.0638,
                        0.1941,  0.2771],
                      [-0.2011,  0.3143,  0.0317,  0.0947, -0.1041, -0.2499,  0.2555, -0.2850,
                       -0.1223,  0.0376],
                      [ 0.2990,  0.0105, -0.0436,  0.2773,  0.0673, -0.1720,  0.0293,  0.0463,
                       -0.1830,  0.0466]])),
             ('fc1.bias', tensor([0.0295, 0.2434, 0.0940, 0.0825, 0.0175])),
             ('fc2.weight',
              tensor([[ 0.3498,  0.1448,  0.2090, -0.2425, -0.2384],
                      [ 0.3390, -0.3021,  0.3031, -0.2717, -0.1913]])),
             ('fc2.bias', tensor([-0.2

# Create a new simpleNN instance and load saved weights
We create a new model instance which will initialize to random weights.
Later we update model with weights saved from our saved weights file

In [36]:
simpleNN2 = SimpleNN(10, 5, 2)

In [37]:
simpleNN2.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.0076,  0.1020, -0.0166,  0.2863,  0.1154, -0.0625,  0.1471, -0.2762,
                       -0.0199, -0.1594],
                      [ 0.2407, -0.1163,  0.1315,  0.0423,  0.2353, -0.2161,  0.0976,  0.1365,
                       -0.0839,  0.0256],
                      [-0.2097, -0.2250, -0.3008, -0.1220, -0.1416,  0.2970,  0.2111, -0.0796,
                        0.0311,  0.0188],
                      [ 0.0165,  0.1525,  0.0448,  0.1531, -0.0604,  0.1606,  0.1225,  0.0734,
                       -0.1851,  0.1884],
                      [-0.2744,  0.0800,  0.2783, -0.1423, -0.1872, -0.0321, -0.2963, -0.0399,
                       -0.2470,  0.3038]])),
             ('fc1.bias',
              tensor([-0.2457, -0.1883, -0.0295,  0.0472, -0.0949])),
             ('fc2.weight',
              tensor([[ 0.0720,  0.0069, -0.3178,  0.0202,  0.3068],
                      [ 0.2276, -0.3540, -0.2972, -0.1282, -0.3491]])),
             ('fc2.

Apply saved weights and show them

In [41]:
simpleNN2.load_state_dict(model_weights_for_simpleNN)
simpleNN2.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.2117,  0.0977,  0.1019,  0.1360, -0.0090,  0.1788,  0.2858,  0.0869,
                        0.2018, -0.3115],
                      [-0.0054, -0.0701,  0.0437, -0.0901,  0.1675, -0.0519,  0.0745,  0.2853,
                        0.0275, -0.1648],
                      [ 0.1453, -0.0004,  0.0510,  0.0302,  0.1480,  0.0504,  0.1632, -0.0638,
                        0.1941,  0.2771],
                      [-0.2011,  0.3143,  0.0317,  0.0947, -0.1041, -0.2499,  0.2555, -0.2850,
                       -0.1223,  0.0376],
                      [ 0.2990,  0.0105, -0.0436,  0.2773,  0.0673, -0.1720,  0.0293,  0.0463,
                       -0.1830,  0.0466]])),
             ('fc1.bias', tensor([0.0295, 0.2434, 0.0940, 0.0825, 0.0175])),
             ('fc2.weight',
              tensor([[ 0.3498,  0.1448,  0.2090, -0.2425, -0.2384],
                      [ 0.3390, -0.3021,  0.3031, -0.2717, -0.1913]])),
             ('fc2.bias', tensor([-0.2

# Save entire model as a file
Instead of state dict save the entire model in a file

In [42]:
torch.save(simpleNN2, "simpleNN.pt")

In [48]:
simpleNN3 = torch.load("simpleNN.pt")
# To ensure we are not in training model
# If eval() is not called before inference, it can yield inconsistent results
simpleNN3.eval()

SimpleNN(
  (fc1): Linear(in_features=10, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=2, bias=True)
)

In [49]:
simpleNN3.state_dict()

OrderedDict([('fc1.weight',
              tensor([[ 0.2117,  0.0977,  0.1019,  0.1360, -0.0090,  0.1788,  0.2858,  0.0869,
                        0.2018, -0.3115],
                      [-0.0054, -0.0701,  0.0437, -0.0901,  0.1675, -0.0519,  0.0745,  0.2853,
                        0.0275, -0.1648],
                      [ 0.1453, -0.0004,  0.0510,  0.0302,  0.1480,  0.0504,  0.1632, -0.0638,
                        0.1941,  0.2771],
                      [-0.2011,  0.3143,  0.0317,  0.0947, -0.1041, -0.2499,  0.2555, -0.2850,
                       -0.1223,  0.0376],
                      [ 0.2990,  0.0105, -0.0436,  0.2773,  0.0673, -0.1720,  0.0293,  0.0463,
                       -0.1830,  0.0466]])),
             ('fc1.bias', tensor([0.0295, 0.2434, 0.0940, 0.0825, 0.0175])),
             ('fc2.weight',
              tensor([[ 0.3498,  0.1448,  0.2090, -0.2425, -0.2384],
                      [ 0.3390, -0.3021,  0.3031, -0.2717, -0.1913]])),
             ('fc2.bias', tensor([-0.2